version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/ProyectoDeAula
      - REDIS_URL=redis://redis:6379
    networks:
      - backend

  mongo:
  
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:

